version: "3"
networks:
    highfive:
services:
    mariadb:
        build: ./database
        restart: unless-stopped
        env_file: ./.env
        environment:
          - MYSQLDB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
          - MYSQLDB_DATABASE=$MARIADB_DATABASE
          - MYSQL_USER=$MARIADB_USER
        networks:
          highfive:
    backend:
        depends_on:
          - mariadb
        build: ./backend
        container_name: "backend"
        volumes:
          - ./backend:/backend
        env_file: ./.env
        ports:
          - 3000:3000
        networks:
          highfive:
        restart: "always"
    webapp_kund:
        depends_on:
          - backend
        build: ./webapp_kund
        container_name: "webapp_kund"
        volumes:
          - ./webapp_kund:/webapp_kund
        ports:
          - '3001:3000'
        networks:
          highfive:
    webapp_admin:
        depends_on:
          - backend
        build: ./webapp_admin
        container_name: "webapp_admin"
        volumes:
          - ./webapp_admin:/webapp_admin
        ports:
          - '3002:3000'
        networks:
          highfive:
    scooter_brain:
        depends_on:
          - backend
        build: ./scooter_brain
        container_name: "scooter_brain"
        volumes:
          - ./scooter_brain:/scooter_brain
        env_file: ./.env
        networks:
          highfive:
        links:
            - backend:backend
        restart: "always"
    mobilapp:
        build: 
          context: ./mobilapp_kund
        container_name: "mobilapp_kund"
        environment:
          - EXPO_DEVTOOLS_LISTEN_ADRESS=0.0.0.0
          - REACT_NATIVE_PACKAGER_HOSTNAME=${IP}
        tty: true
        volumes:
          - ./mobilapp_kund:/mobilapp_kund
        env_file: ./.env
        # command: npm start
        ports:
          - '19001:19001'
          - '19002:19002'
          - '19000:19000'
        healthcheck:
          disable: true
        networks:
          highfive:
