version: "3"
networks:
    highfive:
services:
    mariadb:
        build: ./database
        restart: unless-stopped
        env_file: ./.env
        environment:
          - MYSQLDB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
          - MYSQLDB_DATABASE=$MARIADB_DATABASE
        networks:
          highfive:
    server:
        depends_on:
          - mariadb
        build: ./backend
        container_name: "highfive-server"
        env_file: ./.env
        ports:
          - 3000:3000
        networks:
          highfive:
        restart: "always"
    webapp_kund:
        build: ./webapp_kund
        container_name: "webapp_kund"
        volumes:
          - ./webapp_kund:/app_kund
        ports:
          - '3001:3000'
        networks:
          highfive:
    webapp_admin:
        build: ./webapp_admin
        container_name: "webapp_admin"
        volumes:
          - ./webapp_admin:/app_admin
        ports:
          - '3002:3000'
        networks:
          highfive:
