version: "3"
networks:
    highfive:
services:
    mysqldb:
        build: ./database
        restart: unless-stopped
        env_file: ./.env
        environment:
          - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
          - MYSQL_DATABASE=$MYSQLDB_DATABASE
        networks:
          highfive:
    server:
        depends_on:
          - mysqldb
        build: ./backend
        container_name: "highfive-server"
        env_file: ./.env
        ports:
          - 3000:3000
        networks:
          highfive:
        restart: "always"