# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    env:
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: root
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      
      with:
        node-version: 14.x
        cache: 'npm'
        cache-dependency-path: webapp_admin/package-lock.json
    - name: Setup database
      working-directory: ./backend/test/testDb
      run: |
        pwd
        ls
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        mysql -e "source ddl-test.sql;" -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - run: npm install --legacy-peer-deps
    - run: npm test

