name: High5 Action Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  webapp_admin:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp_admin

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: webapp_admin/package-lock.json
    - run: npm ci
    - run: npm test

  webapp_kund:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp_kund

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: webapp_kund/package-lock.json
    - run: npm ci
    - run: npm test
  
  mobilapp_kund:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobilapp_kund

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: mobilapp_kund/package-lock.json
    - run: npm install --legacy-peer-deps && npm install -g expo-cli
    - run: npm test

  backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    env:
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: root
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      
      with:
        node-version: 14.x
        cache: 'npm'
        cache-dependency-path: webapp_admin/package-lock.json
    - name: Setup database
      working-directory: ./backend/test/testDb
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        mysql -e "source ddl-test.sql;" -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - run: npm install --legacy-peer-deps
    - run: npm test
